name: Build & Deploy Website

on:
  workflow_dispatch:
  push:
    paths:
      - 'docs/**'
    branches:
      - main
  pull_request:

jobs:
  weebsite-build:
    name: Build Website
    runs-on: ubuntu-18.04
    defaults:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/website'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs