name: Update Outdated Packages

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 6 * * 1' # 6am every monday

jobs:
  outdated:
    name: Update Outdated Packages
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup dotnet
        uses: actions/setup-dotnet@v3.0.0
        with:
          dotnet-version: "5.0.x"

      - name: install dotnet-outdated
        run: |
          dotnet tool install --global dotnet-outdated-tool
          dotnet tool update --global dotnet-outdated-tool

      - name: checkout new branch
        run: git checkout -b dotnet-outdated

        # running dotnet restore because `dotnet outdated` was failing if this wasn't run first
      - name: run dotnet restore
        run: dotnet restore

      - name: run dotnet outdated
        id: outdated
        run: |
          if dotnet outdated -u -f -vl major ; then
            echo "::set-output name=has_changes::no"
          else
            echo "::set-output name=has_changes::yes"
          fi

      - name: commit and push changes
        run: |
          if [ "${{ steps.outdated.outputs.has_changes }}" = "no" ] ; then
            echo "No updates today"
          else
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m 'TDDO-0 - dotnet-outdated updates - minor and patch'
            git push --set-upstream origin dotnet-outdated
          fi

      - name: create pr
        run: |
          if [ "${{ steps.outdated.outputs.has_changes }}" = "no" ] ; then
            echo "No updates today"
          else
            curl --request POST \
              --url https://api.github.com/repos/${{ github.repository }}/pulls \
              --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
              --header 'content-type: application/json' \
              --data '{ "title": "TDDO-0 - dotnet-outdated updates", "body": "Minor and Patch package updates", "head": "dotnet-outdated", "base": "master"}'
          fi
